language: objective-c
xcode_workspace: MBEventHandling.xcworkspace
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

script:
- set -o pipefail && xcodebuild -workspace MBEventHandling.xcworkspace -scheme 'MBEventHandling' -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean build | xcpretty
- set -o pipefail && xcodebuild -workspace MBEventHandling.xcworkspace -scheme 'MBEventHandling' -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' test | xcpretty
